version: "3.1"
services:

  database:
    build: ./src/database/
    container_name: database_wl
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/PycharmProjects/data/postgres

  app :
    build: ./
    container_name: app_wl
    restart: always
    ports:
      - "8000:8000"

#  adminer:
#    image: adminer
#    container_name: app_word_learn
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - "8080:8080"


